version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/transcripts
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0

  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transcripts
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
