FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# EXPOSE 9000  # Not needed if not using port 9000
EXPOSE 9001

CMD ["python", "app/main_flask_ui.py"]
